CREATE DATABASE IF NOT EXISTS steemo_db;
USE steemo_db;
CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  celular VARCHAR(20) NOT NULL,
  nivel ENUM('usuario','administrador') NOT NULL,
  senha VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
